import type { Metadata } from 'next';
import { fustat } from '@/theme/fonts';
import { i18nNamespaces } from '@/lib/i18n/config';
import { getI18nResources } from '@/lib/i18n/server';
import { AppProviders } from '@/components/AppProviders';
import '@/theme/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { locale, resources } = await getI18nResources();

  return (
    <html lang={locale} className={fustat.variable}>
      <body className="antialiased">
        <AppProviders
          locale={locale}
          namespaces={i18nNamespaces}
          resources={resources}
        >
          <main>{children}</main>
        </AppProviders>
      </body>
    </html>
  );
}
