import {
  Activity,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarClock,
  Clock,
  FileText,
  LayoutDashboard,
  LogOut,
  Phone,
  Settings,
  ShieldCheck,
  Stethoscope,
  User,
  UserCog,
  UserPlus,
  Users,
  type LucideIcon,
} from 'lucide-react';

export const IconMap: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  appointments: CalendarClock,
  patients: Activity,
  users: Users,
  doctor: Stethoscope,
  receptionist: Phone,
  admin: UserCog,
  invitation: UserPlus,
  roles: ShieldCheck,
  branch: Building2,
  services: Briefcase,
  schedule: Clock,
  clinic: Building,
  profile: User,
  settings: Settings,
  logout: LogOut,
  // legacy keys
  bookings: Calendar,
  quotes: FileText,
  availability: Clock,
  tenant: Building2,
};
