export const ErrorCodes = {
  system: {
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    CONFLICT: 'CONFLICT',
  },
  auth: {
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    FORBIDDEN: 'FORBIDDEN',
    TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
    EMAIL_OR_PASSWORD_INCORRECT: 'EMAIL_OR_PASSWORD_INCORRECT',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    INVITATION_PENDING: 'INVITATION_PENDING',
  },
  validation: {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
  }

} as const;