import { Metadata } from 'next';

interface appConfig {
  metadata: Metadata;
}

export const APP_CONFIG: appConfig = {
  metadata: {
    title: 'Create Next App',
    description: 'Generated by create next app',
  },
};
