import { ROLES, type RoleType } from "../constants/index.ts";
import { PERMISSIONS, type PermissionType } from "../core/permissions.ts";

export type RolesPermissionsMatrixItem = {
  role: RoleType;
  permissions: readonly PermissionType[];
};

export const rolesPermissionsMatrix = [
  {
    role: ROLES.SUPERADMIN,
    permissions: Object.values(PERMISSIONS)
  },
  {
    role: ROLES.ADMIN,
    permissions: [
      ...Object.values(PERMISSIONS).filter(p => !p.includes('-role') && p !== PERMISSIONS.DELETE_CLINIC)
    ]
  },
  {
    role: ROLES.DOCTOR,
    permissions: [
      PERMISSIONS.LIST_CLINIC, PERMISSIONS.GET_CLINIC,
      PERMISSIONS.LIST_SERVICE, PERMISSIONS.GET_SERVICE,
      PERMISSIONS.LIST_BRANCH, PERMISSIONS.GET_BRANCH,
      PERMISSIONS.LIST_WORKER, PERMISSIONS.GET_WORKER,
      PERMISSIONS.LIST_SCHEDULE, PERMISSIONS.GET_SCHEDULE, PERMISSIONS.UPDATE_SCHEDULE,
      PERMISSIONS.LIST_PATIENT, PERMISSIONS.GET_PATIENT, PERMISSIONS.UPDATE_PATIENT,
      PERMISSIONS.LIST_APPOINTMENT, PERMISSIONS.GET_APPOINTMENT, PERMISSIONS.UPDATE_APPOINTMENT, PERMISSIONS.CREATE_APPOINTMENT,
      PERMISSIONS.LIST_NOTIFICATION, PERMISSIONS.GET_NOTIFICATION, PERMISSIONS.UPDATE_NOTIFICATION,
    ]
  },
  {
    role: ROLES.RECEPTIONIST,
    permissions: [
      PERMISSIONS.LIST_CLINIC, PERMISSIONS.GET_CLINIC,
      PERMISSIONS.LIST_SERVICE, PERMISSIONS.GET_SERVICE,
      PERMISSIONS.LIST_BRANCH, PERMISSIONS.GET_BRANCH,
      PERMISSIONS.LIST_WORKER, PERMISSIONS.GET_WORKER,
      PERMISSIONS.LIST_SCHEDULE, PERMISSIONS.GET_SCHEDULE,
      PERMISSIONS.CREATE_PATIENT, PERMISSIONS.LIST_PATIENT, PERMISSIONS.GET_PATIENT, PERMISSIONS.UPDATE_PATIENT,
      PERMISSIONS.CREATE_APPOINTMENT, PERMISSIONS.LIST_APPOINTMENT, PERMISSIONS.GET_APPOINTMENT, PERMISSIONS.UPDATE_APPOINTMENT, PERMISSIONS.DELETE_APPOINTMENT,
      PERMISSIONS.LIST_NOTIFICATION, PERMISSIONS.GET_NOTIFICATION, PERMISSIONS.UPDATE_NOTIFICATION,
    ]
  }
] as const satisfies readonly RolesPermissionsMatrixItem[];
